/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'vulchivivek' at '9/26/17 10:04 AM' with Gradle 2.14.1
 *
 * @author vulchivivek, @date 9/26/17 10:04 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
